#!/bin/bash

DAY=$(date +%d)

# Override default day with first arg
if [ -v 1 ]; then 
  DAY=$1
fi


DIR="$(date +%Y)/day$DAY/"
if mkdir $DIR; then 
  cp -a template/. $DIR
  cd $DIR && aocfetch -day $DAY
fi
